#!/bin/sh
# ============================================================================
#  scripts/build.sh -- the single build path for this project.
#
#  The Makefile is a thin wrapper around this script, so `make` and the
#  OpenFPGA Deck produce the same netlist, the same place-and-route result and
#  the same bitstream, at the same paths:
#
#    build/yosys/top.json          yosys synth_gowin
#    build/pnr/top.pnr.json        nextpnr-himbaechel (+ build/reports/pnr.json)
#    build/bitstream/<name>.fs     gowin_pack; scripts/prog.sh loads it
#    build/logs/                   yosys, nextpnr, gowin_pack logs
#
#  Do not add build flags anywhere else.  The flags below are the ones the
#  Deck uses and the ones this design has been hardware-validated with; they
#  used to differ between the Makefile and this script, which meant two
#  different flows could both report success.
#
#  Tools come from the Deck's OSS CAD Suite (scripts/toolchain.sh).  Sources,
#  project name and constraints come from fpga.yaml; the timing target from
#  VM_PIXEL_HZ in src/hdmi/hdmi_defs.vh.
#
#  Usage:
#    scripts/build.sh            synth + pnr + pack
#    scripts/build.sh --synth    yosys only
#    scripts/build.sh --pnr      nextpnr only (needs build/yosys/top.json)
#    scripts/build.sh --pack     gowin_pack only (needs build/pnr/top.pnr.json)
# ============================================================================
set -e

root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root"
. scripts/toolchain.sh

want_synth=1
want_pnr=1
want_pack=1
case "$1" in
    --synth) want_pnr=0; want_pack=0 ;;
    --pnr)   want_synth=0; want_pack=0 ;;
    --pack)  want_synth=0; want_pnr=0 ;;
    "")      ;;
    *) echo "usage: $0 [--synth|--pnr|--pack]" >&2; exit 2 ;;
esac

name=$(sed -n 's/^name: *//p' fpga.yaml)
cst=$(awk '/^constraints:/ {on=1; next} /^[^ ]/ {on=0} on && /^ *- / {print $2}' fpga.yaml)
mhz=$(awk '/`define VM_PIXEL_HZ/ {print $3 / 1e6}' src/hdmi/hdmi_defs.vh)

mkdir -p build/yosys build/pnr build/reports build/bitstream build/logs

if [ "$want_synth" = 1 ]; then
    {
        echo "# synth.ys -- generated by scripts/build.sh, overwritten on every run."
        echo "# Project: $name"
        echo "# Board:   Sipeed Tang Nano 20K (GW2AR-LV18QN88C8/I7)"
        echo
        # src/sdram/ is a vendored SystemVerilog-flavoured file (a variable
        # declared in an unnamed block); everything else is plain Verilog.
        scripts/sources.sh | sed -e 's|^|read_verilog -noblackbox |' \
                                 -e 's|^\(read_verilog -noblackbox \)\(src/sdram/\)|\1-sv \2|'
        echo
        echo "synth_gowin -top top -json build/yosys/top.json"
    } > build/yosys/synth.ys

    echo "== yosys ($(yosys -V | cut -d' ' -f2))"
    yosys -q -l build/logs/synthesis.log -s build/yosys/synth.ys
fi

if [ "$want_pnr" = 1 ]; then
    test -s build/yosys/top.json || { echo "missing build/yosys/top.json; run $0 --synth first" >&2; exit 1; }
    echo "== $NEXTPNR"
    $NEXTPNR -q -l build/logs/pnr.log \
        --device GW2AR-LV18QN88C8/I7 --vopt family=GW2A-18C \
        --vopt "cst=$cst" --freq "$mhz" \
        --json build/yosys/top.json --write build/pnr/top.pnr.json \
        --report build/reports/pnr.json

    # Gate on the achieved Fmax rather than letting nextpnr's exit status
    # decide.  The design has a wide margin (both clocks pass at 27 MHz), so a
    # silent timing regression is the thing worth catching, not a build
    # failure.  The log carries a placement estimate and a post-route result
    # per clock; taking the minimum of all of them is the conservative choice.
    # constraints/top.sdc is the stricter alternative: it declares each clock
    # domain explicitly instead of applying --freq to all of them.
    grep "Max frequency" build/logs/pnr.log || true
    worst=$(awk '/Max frequency for clock/ {
                     for (i = 1; i <= NF; i++)
                         if ($i == "clock")
                             printf "%s %s\n", $(i + 1), $(i + 2)
                 }' build/logs/pnr.log |
            tr -d "':" |
            sort -k2 -g |
            head -1)
    if [ -n "$worst" ]; then
        clk_name=$(echo "$worst" | cut -d' ' -f1)
        fmax=$(echo "$worst" | cut -d' ' -f2)
        echo "worst clock: $clk_name at $fmax MHz (target $mhz MHz)"
        if awk -v f="$fmax" -v m="$mhz" 'BEGIN { exit !(f + 0 < m + 0) }'; then
            echo "FAILED: $clk_name Fmax $fmax MHz is below the $mhz MHz target" >&2
            echo "        see build/logs/pnr.log for the critical path" >&2
            exit 1
        fi
    else
        echo "warning: no 'Max frequency' line in build/logs/pnr.log; cannot check timing" >&2
    fi
fi

if [ "$want_pack" = 1 ]; then
    test -s build/pnr/top.pnr.json || { echo "missing build/pnr/top.pnr.json; run $0 --pnr first" >&2; exit 1; }
    echo "== gowin_pack"
    gowin_pack -d GW2A-18C -o "build/bitstream/$name.fs" build/pnr/top.pnr.json \
        2>&1 | grep -v -i "not available\|warnings.warn" || true
    test -s "build/bitstream/$name.fs"
    echo "bitstream: build/bitstream/$name.fs"
fi
