# ============================================================================
#  scripts/build.ps1 -- the single build path for this project.
#
#  Mirrors scripts/build.sh exactly.  Outputs to the same directories so the
#  OpenFPGA Deck and this script are interchangeable:
#
#    build\yosys\top.json          yosys synth_gowin
#    build\pnr\top.pnr.json        nextpnr-himbaechel (+ build\reports\pnr.json)
#    build\bitstream\<name>.fs     gowin_pack
#    build\logs\                   yosys, nextpnr, gowin_pack logs
#
#  Usage:
#    scripts\build.ps1             synth + pnr + pack  (default)
#    scripts\build.ps1 -Synth      yosys only
#    scripts\build.ps1 -Pnr        nextpnr only (needs build\yosys\top.json)
#    scripts\build.ps1 -Pack       gowin_pack only (needs build\pnr\top.pnr.json)
# ============================================================================
[CmdletBinding(DefaultParameterSetName = 'All')]
param(
    [Parameter(ParameterSetName = 'Synth')][switch]$Synth,
    [Parameter(ParameterSetName = 'Pnr')]  [switch]$Pnr,
    [Parameter(ParameterSetName = 'Pack')] [switch]$Pack
)
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
Set-Location $root
. (Join-Path $PSScriptRoot 'toolchain.ps1')

$wantSynth = -not ($Pnr -or $Pack)
$wantPnr   = -not ($Synth -or $Pack)
$wantPack  = -not ($Synth -or $Pnr)

# ── Parse fpga.yaml ─────────────────────────────────────────────────────────
$yaml = Get-Content (Join-Path $root 'fpga.yaml') -Raw

$name = ($yaml -split "`n" | Where-Object { $_ -match '^name:\s*(.+)' } | Select-Object -First 1) -replace '^name:\s*', ''
$name = $name.Trim()

# constraints: block -> first '- <file>'
$cst = ''
$inCst = $false
foreach ($line in $yaml -split "`n") {
    if ($line -match '^constraints:') { $inCst = $true; continue }
    if ($inCst -and $line -match '^[^ ]') { $inCst = $false }
    if ($inCst -and $line -match '^\s*-\s+(\S+)') { $cst = $Matches[1].Trim(); break }
}

# VM_PIXEL_HZ from src/hdmi/hdmi_defs.vh
$defsVh = Get-Content (Join-Path $root 'src\hdmi\hdmi_defs.vh') -Raw
$mhz = 0.0
if ($defsVh -match '`define\s+VM_PIXEL_HZ\s+(\d+)') {
    $mhz = [double]$Matches[1] / 1e6
}

# ── Output directories ───────────────────────────────────────────────────────
foreach ($d in @('build\yosys','build\pnr','build\reports','build\bitstream','build\logs')) {
    New-Item -ItemType Directory -Force -Path (Join-Path $root $d) | Out-Null
}

# ── Synthesis ────────────────────────────────────────────────────────────────
if ($wantSynth) {
    $synthYs = Join-Path $root 'build\yosys\synth.ys'

    # Build the yosys script content
    $sources = & (Join-Path $PSScriptRoot 'sources.ps1')
    $lines = @(
        "# synth.ys -- generated by scripts/build.ps1, overwritten on every run.",
        "# Project: $name",
        "# Board:   Sipeed Tang Nano 20K (GW2AR-LV18QN88C8/I7)",
        ""
    )
    foreach ($src in $sources) {
        # src/sdram/ is vendored SystemVerilog; everything else is plain Verilog
        if ($src -match '^src/sdram/') {
            $lines += "read_verilog -noblackbox -sv $src"
        } else {
            $lines += "read_verilog -noblackbox $src"
        }
    }
    $lines += ""
    # synth_gowin -run begin:map_luts  →  abc (AIGER1, no Windows bug)  →  synth_gowin -run map_cells:
    # Workaround for yosys 0.69+156 Windows build: abc9 uses write_xaiger2 which
    # asserts `data_start == f->tellp()` and crashes because Windows opens the file
    # in text mode, shifting byte positions. Plain `abc -lut 4` uses the older
    # AIGER1 path and is unaffected.  Quality impact is minimal for this design
    # (both clocks pass timing with >2x margin).
    $lines += "synth_gowin -run begin:map_luts -top top"
    $lines += "abc -lut 4"
    $lines += "clean"
    $lines += "synth_gowin -run map_cells: -top top -json build/yosys/top.json"
    [System.IO.File]::WriteAllText($synthYs, ($lines -join "`n"), [System.Text.UTF8Encoding]::new($false))

    $yosysExe = if ($OssCadBin) { Join-Path $OssCadBin 'yosys.exe' } else { 'yosys' }
    $yosysVersion = (& $yosysExe --version 2>&1) -replace '^Yosys\s+', '' -replace '\s.*', ''
    Write-Host "== yosys ($yosysVersion)"
    Invoke-Tool 'yosys' @('-q', '-l', 'build/logs/synthesis.log', '-s', 'build/yosys/synth.ys')
}

# ── Place and Route ──────────────────────────────────────────────────────────
if ($wantPnr) {
    $jsonIn = Join-Path $root 'build\yosys\top.json'
    if (-not (Test-Path $jsonIn) -or (Get-Item $jsonIn).Length -eq 0) {
        throw "missing build\yosys\top.json; run scripts\build.ps1 -Synth first"
    }

    Write-Host "== $($script:NextPnr)"
    & $script:NextPnr `
        -q -l 'build/logs/pnr.log' `
        '--device' 'GW2AR-LV18QN88C8/I7' `
        '--vopt' 'family=GW2A-18C' `
        '--vopt' "cst=$cst" `
        '--freq'  "$mhz" `
        '--json'  'build/yosys/top.json' `
        '--write' 'build/pnr/top.pnr.json' `
        '--report' 'build/reports/pnr.json'
    if ($LASTEXITCODE -ne 0) { throw "nextpnr exited with code $LASTEXITCODE" }

    # ── Timing check (mirrors the awk/sort logic in build.sh) ────────────────
    $pnrLog = Get-Content (Join-Path $root 'build\logs\pnr.log') -ErrorAction SilentlyContinue
    $maxFreqLines = $pnrLog | Select-String 'Max frequency'
    $maxFreqLines | ForEach-Object { Write-Host $_.Line }

    # Extract "clock <name>: <fmax> MHz" entries, find the minimum
    $entries = @()
    foreach ($l in ($pnrLog | Select-String 'Max frequency for clock')) {
        if ($l.Line -match "clock\s+'?([^':]+)'?\s*[:\s]+(\d+(?:\.\d+)?)\s+MHz") {
            $entries += [PSCustomObject]@{ Clock = $Matches[1].Trim(); Fmax = [double]$Matches[2] }
        }
    }

    if ($entries.Count -gt 0) {
        $worst = $entries | Sort-Object Fmax | Select-Object -First 1
        Write-Host "worst clock: $($worst.Clock) at $($worst.Fmax) MHz (target $mhz MHz)"
        if ($worst.Fmax -lt $mhz) {
            throw "FAILED: $($worst.Clock) Fmax $($worst.Fmax) MHz is below the $mhz MHz target`n        see build\logs\pnr.log for the critical path"
        }
    } else {
        Write-Warning "no 'Max frequency' line in build\logs\pnr.log; cannot check timing"
    }
}

# ── Pack ─────────────────────────────────────────────────────────────────────
if ($wantPack) {
    $pnrJson = Join-Path $root 'build\pnr\top.pnr.json'
    if (-not (Test-Path $pnrJson) -or (Get-Item $pnrJson).Length -eq 0) {
        throw "missing build\pnr\top.pnr.json; run scripts\build.ps1 -Pnr first"
    }

    Write-Host "== gowin_pack"
    $fsOut = "build/bitstream/$name.fs"
    Invoke-Tool 'gowin_pack' @('-d', 'GW2A-18C', '-o', $fsOut, 'build/pnr/top.pnr.json')

    $fsPath = Join-Path $root "build\bitstream\$name.fs"
    if (-not (Test-Path $fsPath) -or (Get-Item $fsPath).Length -eq 0) {
        throw "gowin_pack did not produce $fsPath"
    }
    Write-Host "bitstream: build\bitstream\$name.fs"
}
