#!/bin/sh
# ============================================================================
#  scripts/build.sh -- the OpenFPGA Deck build, from the command line
#
#  Runs the same steps with the same tools, arguments and output paths as the
#  Deck's Synthesize / Place & Route / Build commands, so either one can build
#  and the other can program the result:
#
#    build/yosys/synth.ys             generated exactly as the Deck does
#    build/yosys/top.json             yosys synth_gowin
#    build/pnr/top.pnr.json           nextpnr-himbaechel (+ build/reports/pnr.json)
#    build/bitstream/<name>.fs        gowin_pack; scripts/prog.sh loads it
#
#  Tools come from the Deck's OSS CAD Suite (scripts/toolchain.sh).  Sources,
#  project name and constraints come from fpga.yaml; the timing target from
#  VM_PIXEL_HZ in src/hdmi/hdmi_defs.vh (27 MHz, the Deck's board clock).
# ============================================================================
set -e

root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root"
. scripts/toolchain.sh

name=$(sed -n 's/^name: *//p' fpga.yaml)
cst=$(awk '/^constraints:/ {on=1; next} /^[^ ]/ {on=0} on && /^ *- / {print $2}' fpga.yaml)
mhz=$(awk '/`define VM_PIXEL_HZ/ {print $3 / 1e6}' src/hdmi/hdmi_defs.vh)

mkdir -p build/yosys build/pnr build/reports build/bitstream build/logs

{
    echo "# synth.ys — generated by OpenFPGA Deck, overwritten on every synthesis run."
    echo "# Project: $name"
    echo "# Board:   Sipeed Tang Nano 20K (GW2AR-LV18QN88C8/I7)"
    echo "# Edit fpga.yaml and re-run \"OpenFPGA Deck: Synthesize\"; do not edit this file."
    echo
    scripts/sources.sh | sed 's/^/read_verilog -noblackbox /'
    echo
    echo "synth_gowin -top top -json build/yosys/top.json"
} > build/yosys/synth.ys

echo "== yosys ($(yosys -V | cut -d' ' -f2))"
yosys -q -l build/logs/synthesis.log -s build/yosys/synth.ys

echo "== $NEXTPNR"
$NEXTPNR -q -l build/logs/pnr.log \
    --device GW2AR-LV18QN88C8/I7 --vopt family=GW2A-18C \
    --vopt "cst=$cst" --freq "$mhz" \
    --json build/yosys/top.json --write build/pnr/top.pnr.json \
    --report build/reports/pnr.json
grep "Max frequency" build/logs/pnr.log || true

echo "== gowin_pack"
gowin_pack -d GW2A-18C -o "build/bitstream/$name.fs" build/pnr/top.pnr.json \
    2>&1 | grep -v -i "not available\|warnings.warn" || true
test -s "build/bitstream/$name.fs"
echo "bitstream: build/bitstream/$name.fs"
